const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const store={get(k,d){try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}},set(k,v){localStorage.setItem(k,JSON.stringify(v))}};
const state={view:'home',tab:'favorites',tracks:store.get('pulse_tracks',[]),favorites:store.get('pulse_favorites',[]),history:store.get('pulse_history',[]),queue:store.get('pulse_queue',[]),playlists:store.get('pulse_playlists',[]),current:null,playing:false,searchToken:0,yt:null,lyrics:null,lyricsLines:[]};
function icons(){window.lucide&&lucide.createIcons({attrs:{'stroke-width':1.8}})}
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function toast(m){const e=$('#toast');e.textContent=m;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1800)}
function save(){store.set('pulse_tracks',state.tracks);store.set('pulse_favorites',state.favorites);store.set('pulse_history',state.history);store.set('pulse_queue',state.queue);store.set('pulse_playlists',state.playlists)}
function isUrl(v){try{const u=new URL(v);return /youtube\.com|youtu\.be/.test(u.hostname)}catch{return false}}
function ytId(url){try{const u=new URL(url);return u.hostname.includes('youtu.be')?u.pathname.slice(1).split('/')[0]:u.searchParams.get('v')}catch{return null}}
function fromUrl(url){const id=ytId(url);return id?{id:'yt-'+id,videoId:id,title:'YouTube video',artist:'YouTube',url,art:`https://i.ytimg.com/vi/${id}/hqdefault.jpg`}:null}
function card(t){return `<div class="track" data-id="${esc(t.id)}" data-json="${encodeURIComponent(JSON.stringify(t))}"><div class="track-art">${t.art?`<img src="${esc(t.art)}" alt="">`:'<i data-lucide="music-2"></i>'}</div><button class="track-info" data-play="${esc(t.id)}"><b>${esc(t.title)}</b><span>${esc(t.artist)}</span></button><button class="track-menu" data-more="${esc(t.id)}" aria-label="More"><i data-lucide="more-horizontal"></i></button></div>`}
function renderHome(){const a=state.history.slice(0,8);$('#recentList').className=a.length?'track-list':'track-list empty-state';$('#recentList').innerHTML=a.length?a.map(card).join(''):'<i data-lucide="music"></i><p>Belum ada musik.</p><small>Gunakan Search untuk mencari lagu.</small>';$('#favCount').textContent=state.favorites.length;$('#historyCount').textContent=state.history.length;$('#queueCount').textContent=state.queue.length;icons()}
function renderLibrary(){let data=state.tab==='favorites'?state.favorites:state.tab==='history'?state.history:state.queue;if(state.tab==='playlists'){renderPlaylists();return}$('#libraryContent').className=data.length?'track-list':'track-list empty-state';$('#libraryContent').innerHTML=data.length?data.map(card).join(''):'<i data-lucide="library"></i><p>Belum ada item.</p><small>Simpan musik untuk melihatnya di sini.</small>';icons()}
function renderPlaylists(){const box=$('#libraryContent');box.className='playlist-grid';box.innerHTML=`<button class="new-playlist" id="newPlaylist"><i data-lucide="plus"></i><span>New playlist</span></button>`+state.playlists.map(p=>`<button class="playlist-card" data-pl="${esc(p.id)}"><i data-lucide="list-music"></i><b>${esc(p.name)}</b><span>${p.tracks.length} tracks</span></button>`).join('');icons()}
function go(v){if(v==='player'){openPlayer();return}state.view=v;$$('.view').forEach(x=>x.classList.toggle('active',x.dataset.view===v));$$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.nav===v));$('#pageTitle').textContent={home:'Good evening',search:'Find your music',library:'Your library',settings:'Settings'}[v]||'Pulse';renderHome();renderLibrary();icons()}
function add(t){state.tracks=[t,...state.tracks.filter(x=>x.id!==t.id)].slice(0,100);save()}
function play(t){add(t);state.current=t;state.history=[t,...state.history.filter(x=>x.id!==t.id)].slice(0,50);save();$('#miniPlayer').classList.remove('hidden');updatePlayer();openPlayer();loadYT(t,true);}
function updatePlayer(){const t=state.current;if(!t)return;$('#playerTitle').textContent=t.title;$('#playerArtist').textContent=t.artist;$('#miniTitle').textContent=t.title;$('#miniArtist').textContent=t.artist;const art=t.art?`<img src="${esc(t.art)}" alt="">`:'<i data-lucide="music-2"></i>';$('#playerArt').innerHTML=art;$('#miniPlayer .mini-art').innerHTML=art;$('#playBtn').innerHTML=`<i data-lucide="${state.playing?'pause':'play'}"></i>`;$('#miniPlay').innerHTML=`<i data-lucide="${state.playing?'pause':'play'}"></i>`;icons()}
function openPlayer(){$('#playerSheet').classList.add('open');$('#playerSheet').setAttribute('aria-hidden','false');updatePlayer()}
function closePlayer(){$('#playerSheet').classList.remove('open');$('#playerSheet').setAttribute('aria-hidden','true')}
function toggleFav(t=state.current){if(!t)return;const i=state.favorites.findIndex(x=>x.id===t.id);if(i>=0){state.favorites.splice(i,1);toast('Removed from favorites')}else{state.favorites.unshift(t);toast('Added to favorites')}save();renderHome();renderLibrary()}
async function search(v){const box=$('#searchResults');if(!v){box.className='track-list empty-state';box.innerHTML='<i data-lucide="search"></i><p>Mulai mencari musik</p><small>Cari judul/artis atau tempel URL YouTube.</small>';icons();return}if(isUrl(v)){const t=fromUrl(v);box.className='track-list';box.innerHTML=card(t);icons();return}const token=++state.searchToken;box.className='track-list loading';box.innerHTML='<div class="search-loading"><span></span><span></span><span></span><p>Mencari musik…</p></div>';try{const data=await PulseSearch.query(v);if(token!==state.searchToken)return;box.className='track-list';box.innerHTML=data.length?data.map(card).join(''):'<div class="empty-state"><i data-lucide="search-x"></i><p>Tidak ada hasil</p><small>Coba kata kunci lain.</small></div>';icons()}catch(e){if(token!==state.searchToken)return;box.className='track-list empty-state';box.innerHTML=e.message==='API_KEY_MISSING'?'<i data-lucide="key-round"></i><p>API key belum diatur</p><small>Buka Settings → YouTube Data API key.</small>':`<i data-lucide="triangle-alert"></i><p>Pencarian gagal</p><small>${esc(e.message)}</small>`;icons()}}
function loadYT(t,auto=false){if(!t?.videoId)return;const area=$('#ytPlayer');area.classList.remove('hidden');if(!window.YT?.Player){window.__ytPending=t;return}if(state.yt){state.yt.loadVideoById(t.videoId);return}state.yt=new YT.Player('ytPlayer',{height:'100%',width:'100%',videoId:t.videoId,playerVars:{playsinline:1,rel:0,enablejsapi:1},events:{onReady:e=>{if(auto)e.target.playVideo()},onStateChange:e=>{if(e.data===1){state.playing=true;updatePlayer()}if(e.data===2){state.playing=false;updatePlayer()}if(e.data===0){next()}}}})}
window.onYouTubeIframeAPIReady=()=>{if(window.__ytPending)loadYT(window.__ytPending,state.playing)};
function next(){const i=state.queue.findIndex(x=>x.id===state.current?.id);const n=state.queue[i+1]||state.queue[0];if(n)play(n);else state.playing=false;updatePlayer()}
function prev(){const i=state.history.findIndex(x=>x.id===state.current?.id);const n=state.history[i+1];if(n)play(n)}
async function showLyrics(){const area=$('#mediaArea');area.classList.remove('hidden');area.innerHTML='<div class="lyrics"><div class="lyrics-head"><b>Lyrics</b><span>LRCLIB</span></div><p>Loading lyrics…</p></div>';try{const l=await PulseLyrics.get(state.current);if(!l){area.innerHTML='<div class="lyrics"><div class="lyrics-head"><b>Lyrics</b></div><p>Lyrics tidak ditemukan untuk lagu ini.</p></div>';return}state.lyrics=l;state.lyricsLines=PulseLyrics.parse(l.syncedLyrics||l.plainLyrics||'');area.innerHTML=`<div class="lyrics"><div class="lyrics-head"><b>${esc(l.trackName||state.current.title)}</b><span>${esc(l.artistName||state.current.artist)}</span></div><div class="lyrics-body">${state.lyricsLines.map((x,i)=>`<p class="lyric-line" data-li="${i}" data-time="${x.time??''}">${esc(x.text)}</p>`).join('')}</div></div>`}catch(e){area.innerHTML='<div class="lyrics"><p>Lyrics gagal dimuat.</p></div>'}}
function addQueue(){if(!state.current)return;state.queue=[...state.queue,state.current];state.queue=[...new Map(state.queue.map(x=>[x.id,x])).values()];save();renderHome();toast('Added to queue')}
function newPlaylist(t){const name=prompt('Nama playlist:');if(!name?.trim())return;const pl={id:'pl-'+Date.now(),name:name.trim(),tracks:t?[t]:[]};state.playlists.push(pl);save();renderLibrary();toast(t?'Playlist created and track added':'Playlist created')}
function openPlaylist(id){const p=state.playlists.find(x=>x.id===id);if(!p)return;$('#libraryContent').className=p.tracks.length?'track-list':'track-list empty-state';$('#libraryContent').innerHTML=p.tracks.length?p.tracks.map(card).join(''):`<i data-lucide="list-music"></i><p>${esc(p.name)} kosong.</p><small>Tambahkan lagu dari menu track.</small>`;icons()}
$('#searchInput').addEventListener('input',e=>{$('#clearSearch').classList.toggle('hidden',!e.target.value);search(e.target.value.trim())});$('#clearSearch').onclick=()=>{$('#searchInput').value='';$('#clearSearch').classList.add('hidden');search('')};
document.addEventListener('click',e=>{const n=e.target.closest('[data-nav]');if(n)go(n.dataset.nav);const p=e.target.closest('[data-play]');if(p){const t=[...state.tracks,...state.history].find(x=>x.id===p.dataset.play)||JSON.parse(decodeURIComponent(p.closest('.track').dataset.json||'null'));if(t)play(t)}const more=e.target.closest('[data-more]');if(more){const t=[...state.tracks,...state.history].find(x=>x.id===more.dataset.more);if(t){const action=prompt(`Track: ${t.title}\nKetik: f=favorite, q=queue, p=playlist`);if(action==='f')toggleFav(t);if(action==='q'){state.queue.push(t);save();renderHome();toast('Added to queue')}if(action==='p'){if(!state.playlists.length){newPlaylist(t);}else{const names=state.playlists.map((x,i)=>`${i+1}. ${x.name}`).join('\n');const pick=Number(prompt(names+'\n\nNomor playlist:'))-1;if(state.playlists[pick]){state.playlists[pick].tracks=[...state.playlists[pick].tracks.filter(x=>x.id!==t.id),t];save();toast('Added to playlist')}}}}}const pl=e.target.closest('[data-pl]');if(pl)openPlaylist(pl.dataset.pl);if(e.target.closest('#newPlaylist'))newPlaylist()});
$('#favoriteBtn').onclick=()=>toggleFav();$('#openPlayer').onclick=openPlayer;$('#miniPlay').onclick=()=>{$('#playBtn').click()};$('#playBtn').onclick=()=>{if(!state.current){toast('Pilih track terlebih dahulu');return}if(state.yt){state.playing=!state.playing;state.playing?state.yt.playVideo():state.yt.pauseVideo()}else{state.playing=!state.playing}updatePlayer()};$('#nextBtn').onclick=next;$('#prevBtn').onclick=prev;$('#queueBtn').onclick=addQueue;$('#lyricsBtn').onclick=showLyrics;$('#videoBtn').onclick=()=>{$('#ytPlayer').classList.toggle('hidden');$('#mediaArea').classList.add('hidden');};$$('[data-close-player]').forEach(x=>x.onclick=closePlayer);
$$('.tab').forEach(b=>b.onclick=()=>{$$('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.tab=b.dataset.tab;renderLibrary()});
$('#themeBtn').onclick=()=>{document.documentElement.classList.toggle('light');localStorage.setItem('pulse_theme',document.documentElement.classList.contains('light')?'light':'dark')};$('#appearanceSwitch').onclick=()=>{$('#themeBtn').click();$('#appearanceSwitch').classList.toggle('on',!document.documentElement.classList.contains('light'))};$('#autoplaySwitch').onclick=e=>e.currentTarget.classList.toggle('on');
$('#apiKeyBtn').onclick=()=>{const old=PulseSearch.getKey();const key=prompt('Masukkan YouTube Data API v3 key:',old);if(key!==null){PulseSearch.setKey(key);toast(key.trim()?'API key tersimpan':'API key dihapus')}};
$('#clearData').onclick=()=>{if(confirm('Hapus semua data lokal Pulse?')){['pulse_tracks','pulse_favorites','pulse_history','pulse_queue','pulse_playlists','pulse_yt_api_key'].forEach(k=>localStorage.removeItem(k));location.reload()}};
if(localStorage.getItem('pulse_theme')==='light')document.documentElement.classList.add('light');
const y=document.createElement('script');y.src='https://www.youtube.com/iframe_api';document.head.appendChild(y);
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('service-worker.js').catch(()=>{}));renderHome();renderLibrary();icons();

setInterval(()=>{if(!state.yt||!state.lyricsLines.length)return;let t=0;try{t=state.yt.getCurrentTime()}catch{}let idx=-1;state.lyricsLines.forEach((x,i)=>{if(x.time!=null&&x.time<=t)idx=i});$$('.lyric-line').forEach((e,i)=>e.classList.toggle('active',i===idx));const a=$('.lyric-line.active');if(a)a.scrollIntoView({block:'center',behavior:'smooth'})},700);
